v0.2.0

diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check b/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
--- a/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/repo-key-check
@@ -1,28 +1,35 @@
 #!/bin/bash
+
+# SPDX-License-Identifier: AGPL-3.0-only
+
 set -o pipefail
 
-status=0
+declare -i status=0
 
-[[ -n $1 ]] && codename=$1 || exit 1
-
-repo_key="/etc/apt/trusted.gpg.d/proxmox-release-$codename.gpg"
-repo_key_url="https://enterprise.proxmox.com/debian/proxmox-release-$codename.gpg"
-
-echo -n "Checking for Proxmox release key ($codename) ... "
+[[ -n $1 ]] && declare -r repo_key=$1 || exit 1
+[[ -n $2 ]] && declare -r repo_key_url=$2 || exit 1
 
 if [[ -f $repo_key ]]; then
-    echo "already present:"
+    echo "+ Already present:"
 else 
-    echo -n "not present, retrieving... "
+    echo "~ Not present, retrieving: $repo_key_url ..."
     if wget -q "$repo_key_url" -O "$repo_key" 2> /dev/null; then
-        echo "retrieved:"
+        echo "Retrieved:"
     else
-        echo "unable to retrieve or store key." >&2
+        echo "! Errors attempting to retrieve or store key." >&2
         status=1
     fi
 fi
 
-GNUPGHOME=$(mktemp -d /tmp/gnupg-XXXXXX) gpg --show-keys "$repo_key" 2> /dev/null || { echo "Unable to display key details." >&2; status=1; }
-sha512sum "$repo_key" 2> /dev/null | awk '{print "sha512 " $1}' || { echo "Unable to display checksum." >&2; status=1; }
+export GNUPGHOME=$(mktemp -d /tmp/gnupg-XXXXXX) 2> /dev/null
+[[ -d "$GNUPGHOME" ]] || unset GNUPGHOME
+
+gpg --show-keys "$repo_key" 2> /dev/null \
+|| { echo "! Errors examining key details." >&2; status=1; }
+
+[[ -d "$GNUPGHOME" ]] && rm -rf "$GNUPGHOME" 2> /dev/null
+
+{ sha512sum "$repo_key" | awk '{print "sha512 " $1}'; } 2> /dev/null \
+|| { echo "! Errors calculating key checksum." >&2; status=1; }
 
 exit $status
diff --git a/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace b/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
--- a/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
+++ b/free-pmx-no-subscription/usr/lib/free-pmx/repo-list-replace
@@ -1,26 +1,28 @@
 #!/bin/bash
 
-status=0
+# SPDX-License-Identifier: AGPL-3.0-only
 
-[[ -n $1 ]] && old_list=$1 || exit 1
-[[ -n $2 ]] && new_list=$2 || exit 1
-[[ -n $3 ]] && new_source=$3 || exit 1
+declare -i status=0
+
+[[ -n $1 ]] && declare -r old_list=$1 || exit 1
+[[ -n $2 ]] && declare -r new_list=$2 || exit 1
+[[ -n $3 ]] && declare -r new_source=$3 || exit 1
 
 if [[ ! -f $old_list ]]; then
-    echo "Original not present: $old_list"
+    echo "~ Original not present: $old_list"
 elif mv "$old_list"{,.disabled} 2> /dev/null; then
-    echo "Disabled original: $old_list"
+    echo "+ Disabled original: $old_list"
 else
-    echo "Could not disable original: $old_list" >&2
+    echo "! Could not disable original: $old_list" >&2
     status=1
 fi
 
 if [[ -f $new_list ]]; then
-    echo "New NOT created - already present: $new_list"
-elif cat > "$new_list" <<< "$new_source"; then
-    echo "Created new: $new_list"
+    echo "~ New NOT created as already present: $new_list"
+elif { cat > "$new_list" <<< "$new_source"; } 2> /dev/null; then
+    echo "+ Created new: $new_list"
 else
-    echo "Could not create: $new_list" >&2
+    echo "! Could not create: $new_list" >&2
     status=1
 fi
 
